[smtp]
host = "smtp.server.fr"
port = 25
user = "your_user"
pass = "your_pass""

[alert1]
url = "http://hackaday.com/"
subject = "Alerte Hackaday"
from = "robot@yourdomain.com"
to = "dest@yourdoamin.com"
sleep = 360
